In [1]:
import numpy as np
import sympy as sp

In [3]:
# 1. Vectors
v1 = np.array([2, 3, 4])
v2 = np.array([1, 5, 2])

print("\nVector 1 =", v1)
print("Vector 2 =", v2)

# Vector Addition
addition = v1 + v2
print("\nVector Addition =", addition)

# Vector Subtraction
subtraction = v1 - v2
print("Vector Subtraction =", subtraction)

# Magnitude
magnitude = np.linalg.norm(v1)
print("Magnitude of Vector 1 =", magnitude)



Vector 1 = [2 3 4]
Vector 2 = [1 5 2]

Vector Addition = [3 8 6]
Vector Subtraction = [ 1 -2  2]
Magnitude of Vector 1 = 5.385164807134504


In [4]:
# 2. Dot Product
dot = np.dot(v1, v2)
print("\nDot Product =", dot)


Dot Product = 25


In [5]:
# 3. Matrices
A = np.array([[2, 1],
              [1, 3]])

B = np.array([[4, 2],
              [5, 1]])

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nMatrix Addition:\n", A + B)
print("\nMatrix Multiplication:\n", np.matmul(A, B))


Matrix A:
 [[2 1]
 [1 3]]

Matrix B:
 [[4 2]
 [5 1]]

Matrix Addition:
 [[6 3]
 [6 4]]

Matrix Multiplication:
 [[13  5]
 [19  5]]


In [7]:
# 4. Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[1.38196601 3.61803399]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [8]:
# 5. Derivatives
x = sp.Symbol('x')
f = x**3 + 2*x**2 + 5*x + 7

derivative = sp.diff(f, x)

print("\nFunction:")
print("f(x) =", f)

print("\nDerivative:")
print("f'(x) =", derivative)



Function:
f(x) = x**3 + 2*x**2 + 5*x + 7

Derivative:
f'(x) = 3*x**2 + 4*x + 5


In [9]:
# 6. Gradient
x, y = sp.symbols('x y')
f = x**2 + y**2 + x*y

gradient = [sp.diff(f, x), sp.diff(f, y)]

print("\nFunction:")
print("f(x,y) =", f)

print("\nGradient:")
print("∇f =", gradient)


Function:
f(x,y) = x**2 + x*y + y**2

Gradient:
∇f = [2*x + y, x + 2*y]


In [ ]:
# 7. Chain Rule
x = sp.Symbol('x')
u = x**2 + 1
g = sp.sin(u)

chain = sp.diff(g, x)

print("\nFunction:")
print("sin(x² + 1)")

print("\nDerivative using Chain Rule:")
print(chain)